[project]
name = "ray-play"
version = "0.1.0"
requires-python = ">=3.12, <3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "pip>=25.3",
    "ray[default]>=2.53.0",
    "virtualenv>=20.35.4",
]
