apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kagent-ui
  namespace: kagent
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - secretName: tls-kagent-server03-creutz-io
      hosts:
        - "kagent.server03.creutz.io"
  rules:
    - host: kagent.server03.creutz.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kagent-ui
                port:
                  name: kagent-ui
